# .github/workflows/update_news.yml

name: Daily News Update

on:
  # 매일 00:00 UTC (한국 시간 오전 9시)에 워크플로우를 실행합니다.
  schedule:
    - cron: '0 21 * * *'
  
  # GitHub Actions 탭에서 수동으로 이 워크플로우를 실행할 수 있도록 합니다.
  workflow_dispatch:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소의 코드를 가상 머신으로 가져옵니다.
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Konlpy에 필요한 Java(JDK) 환경을 설정합니다.
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. 파이썬 환경을 설정합니다.
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # 4. requirements.txt에 명시된 파이썬 라이브러리를 설치합니다.
      - name: Install Python dependencies
        run: pip install -r scrap/requirements.txt

      # 5. 뉴스 크롤링 스크립트를 실행합니다.
      - name: Run Crawling Script
        run: python scrap/crawl_script.py

      # 6. 스크랩 및 점수 예측 스크립트를 실행합니다.
      - name: Run Scraping Script
        run: python scrap/run_daily_scraping.py

      # 7. GitHub Pages용 정적 파일(news_data.json 등)을 생성합니다.
      - name: Generate Static Files for GitHub Pages
        run: python scrap/generate_static_files.py

      # 8. 변경된 파일(news_data.json)을 자동으로 커밋합니다.
      - name: Commit and push if it changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: Daily news data updated'
          # 특정 파일만 커밋 대상으로 지정할 수 있습니다.
          # 예: file_pattern: scrap/news_data.json
          # 비워두면 변경된 모든 파일을 커밋합니다.
